# Generated by Django 5.2.8 on 2025-11-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePasajero', models.CharField(max_length=200)),
                ('numeroAndenes', models.CharField(max_length=50)),
                ('coche', models.CharField(max_length=10)),
                ('asiento', models.CharField(max_length=10)),
                ('clase', models.CharField(default='Turista', max_length=50)),
                ('origenEstacion', models.CharField(max_length=200)),
                ('horaSalidaOrigen', models.TimeField()),
                ('andenOrigen', models.CharField(max_length=10)),
                ('destinoEstacion', models.CharField(max_length=200)),
                ('horaLlegadaDestino', models.TimeField()),
                ('fechaViaje', models.DateField()),
                ('fechaEmbarque', models.TimeField()),
                ('notificacionesActivas', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='trainLife.usuario')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fechaViaje', '-horaSalidaOrigen'],
            },
        ),
        migrations.CreateModel(
            name='ParadaIntermedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=200)),
                ('horaLlegada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_intermedias', to='trainLife.viaje')),
            ],
            options={
                'verbose_name': 'Parada Intermedia',
                'verbose_name_plural': 'Paradas Intermedias',
                'ordering': ['orden'],
            },
        ),
    ]
