# Generated by Django 5.2.8 on 2025-11-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0002_viaje_paradaintermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='numeroAndenes',
        ),
    ]
