# Generated by Django 5.2.8 on 2025-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0003_remove_viaje_numeroandenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParadaIntermedia',
        ),
    ]
