# Generated by Django 5.2.8 on 2025-11-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0004_delete_paradaintermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fechaEmbarque',
        ),
    ]
