# Generated by Django 5.2.7 on 2025-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0005_remove_viaje_fechaembarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estadoViaje',
            field=models.CharField(default='confirmado', max_length=50),
        ),
    ]
