# Generated by Django 5.2.7 on 2025-11-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0006_viaje_estadoviaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esFavorita', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='trainLife.usuario')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('estacionSalida', models.CharField(max_length=200)),
                ('andenSalida', models.CharField(blank=True, max_length=10, null=True)),
                ('estacionLlegada', models.CharField(max_length=200)),
                ('andenLlegada', models.CharField(blank=True, max_length=10, null=True)),
                ('horaSalida', models.TimeField()),
                ('horaLlegada', models.TimeField()),
                ('nombreLinea', models.CharField(max_length=100)),
                ('colorLinea', models.CharField(blank=True, max_length=50, null=True)),
                ('imagenMapa', models.ImageField(blank=True, null=True, upload_to='trayectos/mapas/')),
                ('numeroTransbordos', models.PositiveIntegerField(default=0)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos', to='trainLife.ruta')),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
                'ordering': ['ruta', 'orden'],
            },
        ),
    ]
