# Generated by Django 5.2.7 on 2025-11-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0007_ruta_trayecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='esFavorita',
        ),
        migrations.AddField(
            model_name='ruta',
            name='esPublica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='trainLife.usuario'),
        ),
        migrations.CreateModel(
            name='RutaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='trainLife.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_favoritas', to='trainLife.usuario')),
            ],
            options={
                'verbose_name': 'Ruta Favorita',
                'verbose_name_plural': 'Rutas Favoritas',
                'ordering': ['-fechaAgregado'],
                'unique_together': {('usuario', 'ruta')},
            },
        ),
    ]
