# Generated by Django 5.2.7 on 2025-11-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0008_remove_ruta_esfavorita_ruta_espublica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='esPublica',
        ),
        migrations.DeleteModel(
            name='RutaFavorita',
        ),
    ]
