# Generated by Django 5.2.7 on 2025-11-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0009_remove_ruta_espublica_delete_rutafavorita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='numeroTransbordos',
        ),
    ]
