# Generated by Django 5.2.7 on 2025-11-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0010_remove_trayecto_numerotransbordos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_viaje', 'Cambio en Viaje'), ('nuevo_viaje', 'Nuevo Viaje'), ('cancelacion', 'Cancelación'), ('recordatorio', 'Recordatorio'), ('cambio_anden', 'Cambio de Andén'), ('cambio_hora', 'Cambio de Hora'), ('alerta', 'Alerta'), ('info', 'Información')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('importante', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaLeida', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trainLife.usuario')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trainLife.viaje')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
