# Generated by Django 5.2.7 on 2025-11-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0011_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trainLife.ruta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cambio_viaje', 'Cambio en Viaje'), ('nuevo_viaje', 'Nuevo Viaje'), ('cancelacion', 'Cancelación'), ('recordatorio', 'Recordatorio'), ('cambio_anden', 'Cambio de Andén'), ('cambio_hora', 'Cambio de Hora'), ('cambio_ruta', 'Cambio en Ruta'), ('alerta', 'Alerta'), ('info', 'Información')], default='info', max_length=20),
        ),
    ]
