# Generated by Django 5.2.7 on 2025-11-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0012_notificacion_ruta_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAviso', models.CharField(max_length=200)),
                ('fechaAviso', models.DateField()),
                ('horaAviso', models.TimeField()),
                ('informacion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fechaAviso', '-horaAviso'],
            },
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='notificacionesActivas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacionesAvisos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacionesRutas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacionesViajes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cambio_viaje', 'Cambio en Viaje'), ('nuevo_viaje', 'Nuevo Viaje'), ('cancelacion', 'Cancelación'), ('recordatorio', 'Recordatorio'), ('cambio_anden', 'Cambio de Andén'), ('cambio_hora', 'Cambio de Hora'), ('cambio_ruta', 'Cambio en Ruta'), ('aviso_general', 'Aviso General'), ('alerta', 'Alerta'), ('info', 'Información')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trainLife.aviso'),
        ),
    ]
