# Generated by Django 5.2.8 on 2025-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0013_aviso_remove_viaje_notificacionesactivas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='rutas', to='trainLife.usuario'),
        ),
    ]
