# Generated by Django 5.2.7 on 2025-12-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0014_remove_ruta_usuario_ruta_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='nombreTren',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='plazasDisponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='nombrePasajero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='trainLife.usuario'),
        ),
    ]
