# Generated by Django 5.2.7 on 2025-12-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0015_viaje_nombretren_viaje_plazasdisponibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='andenOrigen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='asiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='coche',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
