# Generated by Django 5.2.7 on 2025-12-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0016_alter_viaje_andenorigen_alter_viaje_asiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='nombreTren',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='plazasDisponibles',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='precio',
        ),
    ]
