# Generated by Django 5.2.7 on 2025-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0017_remove_viaje_nombretren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estadoViaje',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=50),
        ),
    ]
