# Generated by Django 5.2.7 on 2025-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0018_alter_viaje_estadoviaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estadoViaje',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado'), ('disponible', 'Disponible')], default='confirmado', max_length=50),
        ),
    ]
