# Generated by Django 5.2.8 on 2025-12-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0015_usuario_color_mode'),
        ('trainLife', '0019_alter_viaje_estadoviaje'),
    ]

    operations = [
    ]
