# Generated by Django 5.2.7 on 2025-12-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainLife', '0020_merge_20251228_1834'),
        ('trainLife', '0020_merge_20251228_2042'),
    ]

    operations = [
    ]
